name: www

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Run a generate www"
        run: |
          git config --global user.name unibearsite
          git config --global user.email unibearsite@gmail.com
          
          echo "w" >> README.md
          
          git add README.md
          git commit -m '[add] www'
          git push origin main
